### ISSUE TITLE
Support for headers like Sec-WebSocket-Protocol and Sec-WebSocket-Extensions

### ISSUE THREAD

**Issue by anhmiuhv** [vinted/actioncable-client-kotlin#16]
My ruby server's ActionCable requires this header. Will the library support them in the future?

**Comment by GediminasZukas** [comment]
Hi. Take a look: https://github.com/vinted/actioncable-client-kotlin#options 
We have API for specifying headers: ```options.connection.headers = mapOf("X-Foo" to "Bar")```
Did you tried to use it with your use case?

**Comment by anhmiuhv** [comment]
I have used it and it works well. However, should it be already included in the library as a part of the standard?

**Comment by GediminasZukas** [comment]
@anhmiuhv , could you elaborate more about the problem? As I read `Sec-WebSocket-Protocol` and `Sec-WebSocket-Extensions` headers are used in order to customize standart websocket connection and/or add some extension parameters. Am I correct? If this is the case, I think current mechanism of setting headers is fine for this problem.
